#!/bin/bash
[[ -n "$DEBUG" ]] && set -x

# Constants
dnsmasq_hostsdir="/etc/dnsmasq-hosts.d/"
incus_update_interval="${INCUS_UPDATE_INTERVAL:-300}"  # Update period for Incus polling (seconds)

# Reading Environment Variables
dns_domain="${DNS_DOMAIN:-local.}"
subnet="${SUBNET:-172.17.0.0/16}"
docker_network="${DOCKER_NETWORK:-bridge}"

# PID Placeholders
dnsmasq_pid=""
docker_listener_pid=""
incus_listener_pid=""

# Function - Helper Functions
log() {
  printf '%s\n' "[INFO] $*"
}

ipv4_to_int(){
  # Convert dotted IPv4 into an integer for CIDR comparisons.
  # Input format must be "A.B.C.D".
  local ip="${1}"
  local IFS=.
  read -r a b c d <<< "$ip" || true
  echo $(( (a << 24) + (b << 16) + (c << 8) + d ))
}

ip_in_subnet(){
  # IPv4-only: ip_in_subnet <ip> <cidr>
  # Returns 0 when ip is inside cidr, otherwise 1.
  local ip="${1}"
  local cidr="${2}"

  # Basic validation: require CIDR like "x.x.x.x/NN".
  case "$cidr" in
    */*) ;;
    *)
      return 1
      ;;
  esac

  local subnet_ip="${cidr%%/*}"
  local prefix="${cidr##*/}"

  # Prefix must be 0..32.
  case "$prefix" in
    ''|*[!0-9]*)
      return 1
      ;;
    *)
      ;;
  esac
  [ "$prefix" -ge 0 ] && [ "$prefix" -le 32 ] || return 1

  local mask
  if [ "$prefix" -eq 0 ]; then
    mask=0
  else
    mask=$(( (4294967295 << (32 - prefix)) & 4294967295 ))
  fi

  local ip_int subnet_int
  ip_int="$(ipv4_to_int "$ip")" || return 1
  subnet_int="$(ipv4_to_int "$subnet_ip")" || return 1

  [ $(( ip_int & mask )) -eq $(( subnet_int & mask )) ]
}

# Function - Start dnsmasq
start_dnsmasq(){
  # Start dnsmasq with local-only behavior. Host records come exclusively
  # from files under --hostsdir (generated by this script).
  local args=(--keep-in-foreground --no-hosts --no-resolv --hostsdir="$dnsmasq_hostsdir" --domain-needed --bogus-priv --conf-file="/dev/null")
  if [ -n "$dns_domain" ]; then
    args+=(--domain="$dns_domain" --expand-hosts)
  fi
  dnsmasq "${args[@]}" &
  dnsmasq_pid=$!
}

# Function - Relod dnsmasq config
reload_dnsmasq(){
  # SIGHUP reloads config: https://thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html
  if [ -n "${dnsmasq_pid:-}" ] && kill -0 "$dnsmasq_pid" 2>/dev/null; then
    kill -HUP "$dnsmasq_pid" 2>/dev/null || true
  fi
}

# Function - Stop dnsmasq
stop_dnsmasq(){
  if [ -n "${dnsmasq_pid:-}" ]; then
    kill "$dnsmasq_pid" 2>/dev/null || true
  fi
}

# Function - Update dnsmasq config
update_record(){
  local lockdir="/tmp/container-dns.lock"
  local hostsfile="${dnsmasq_hostsdir}containers"
  local tmprecords="/tmp/container-dns.records.$$"
  local tmpfile="${dnsmasq_hostsdir}containers.tmp.$$"

  # Acquire lock to avoid concurrent rebuilds from listeners.
  while ! mkdir "$lockdir" 2>/dev/null; do
    sleep 1
  done
  trap 'rmdir "$lockdir" 2>/dev/null || true' RETURN

  rm -f "$tmprecords" "$tmpfile"
  : > "$tmprecords"

  if [ -z "$subnet" ]; then
    echo "SUBNET is not set; skipping IP filtering" >&2
  fi

  # For Docker:
  while read -r id name; do
    [ -z "$id" ] && continue

    ip="$(docker inspect -f '{{ (index .NetworkSettings.Networks "'"$docker_network"'").IPAddress }}' "$id" 2>/dev/null || true)"

    # docker sometimes prints placeholders when a network doesn't exist.
    case "$ip" in
      ''|'<no value>'|null)
        continue
        ;;
    esac

    if [ -z "$subnet" ] || ip_in_subnet "$ip" "$subnet"; then
      echo "$ip $name.$dns_domain" >> "$tmprecords"
    fi
  done < <(docker ps --format '{{.ID}} {{.Names}}' 2>/dev/null || true)

  # For Incus:
  while IFS=',' read -r name ip_field; do
    [ -z "$name" ] && continue
    ip_field="${ip_field%% *}"
    ip="${ip_field%%/*}"

    case "$ip" in
      ''|'<no value>'|null)
        continue
        ;;
    esac

    if [ -z "$subnet" ] || ip_in_subnet "$ip" "$subnet"; then
      echo "$ip $name.$dns_domain" >> "$tmprecords"
    fi
  done < <(incus list type=container status=running --force-local --format csv,noheader -c n4 2>/dev/null || true)

  # Sort records so output is deterministic (helps avoid unnecessary reloads).
  sort -u "$tmprecords" > "$tmpfile"

  record_count="$(wc -l < "$tmpfile" | tr -d ' \t')"

  if [ -f "$hostsfile" ] && cmp -s "$tmpfile" "$hostsfile"; then
    rm -f "$tmpfile"
    log "Records checked: ${record_count} record(s); no changes."
  else
    mv -f "$tmpfile" "$hostsfile"
    reload_dnsmasq
    log "Records updated:"
    while IFS= read -r line || [ -n "$line" ]; do
      [ -z "$line" ] && continue
      printf '%s\n' "  - ${line}"
    done < "$hostsfile"
  fi

  rm -f "$tmprecords"
}

# Function - Shutdown
shutdown(){
  log "Stopping..."
  if [ -n "${docker_listener_pid:-}" ]; then
    kill "$docker_listener_pid" 2>/dev/null || true
  fi
  if [ -n "${incus_listener_pid:-}" ]; then
    kill "$incus_listener_pid" 2>/dev/null || true
  fi
  stop_dnsmasq
  exit 0
}

# Listener - Docker listener
listener_docker(){
  while true; do
    # Treat any docker event as a hint that the container set changed.
    # update_record() handles debouncing and reload-on-change.
    while read -r _line; do
      update_record
    done < <(docker events -f event=start -f event=stop -f event=die 2>/dev/null)
    sleep 2
  done
}

# Listener - Incus listener
listener_incus(){
  # Incus has no reliable "events listener" for this usage, so poll.
  while true; do
    update_record
    sleep "$incus_update_interval"
  done
}

# Main

# 1. Preparation
mkdir -p "$dnsmasq_hostsdir"

# 5. Observe shutdown signal (must be set before starting listeners)
trap shutdown SIGINT SIGTERM

# 3. Initial config generation
update_record

# 4. Start dnsmasq
start_dnsmasq

# 5. Setup listeners
listener_docker &
docker_listener_pid=$!
listener_incus &
incus_listener_pid=$!
log "Started."

# Wait forever (or until a listener exits unexpectedly)
wait "$docker_listener_pid" "$incus_listener_pid"
